common/urls.py
from django.contrib.auth import views as auth_views
from common.views import (
    HomePage, account_activation_sent, activate, SignUpView, ProfileView,
    ForgotPasswordView, load_districts, load_counties,load_sub_counties,
    load_parishes,load_villages, activate,ChangePasswordView,account_activated,
    OpenMarketHomePage
)

from django.urls import path,include
from rest_framework import routers
from . import views



router = routers.DefaultRouter()

router.register(r'register', views.UserViewSet,'users')
router.register(r'groups', views.GroupViewSet,'groups')
router.register(r'counties',views.CountyViewSet,'counties')
router.register(r'sub_counties',views.SubCountyViewSet,'sub_counties')
router.register(r'districts', views.DistrictViewSet,'districts')
router.register(r'parishes',views.ParishViewSet,'parishes')
router.register(r'villages',views.VillageViewSet, 'villages')
router.register(r'post_users', views.PostUserDataViewSet, 'post_users')
router.register(r'profiles', views.PostProfileViewSet, 'profiles')
router.register(r'regions',views.RegionViewSet, 'regions')


app_name ='common'

urlpatterns = [
    path('api/', include(router.urls)),
    path('',OpenMarketHomePage.as_view(), name='open_market'),
    path('home', HomePage.as_view(), name='home'),
    path('account/change_password', ChangePasswordView.as_view(), name='change_password'),
    path('account_activation_sent/', account_activation_sent, name='account_activation_sent'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('activate/<uidb64>/<token>/', activate, name='activate'),
    path('account/activated', account_activated, name='activated'),
    path('forgot-password/', ForgotPasswordView.as_view(), name='forgot_password'),
    path('<int:pk>/view/profile', ProfileView.as_view(), name="view_profile"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # load districts url
    path('ajax/load-districts/', load_districts, name='ajax_load_districts'),
    path('ajax/load-counties/', load_counties, name='ajax_load_counties'),
    path('ajax/load-sub_counties/', load_sub_counties, name='ajax_load_sub_counties'),
    path('ajax/load-parishes/', load_parishes, name='ajax_load_parishes'),
    path('ajax/load-villages/', load_villages, name='ajax_load_villages'),

   
] 

farmer/urls.py
from django.urls import include, path
from rest_framework import routers
from . import views
from .views import (GroupList, FarmerProfileList, CreateFarmerProfile, UpdateFarmerProfile,FarmerProfileViewSet
,CreateFarmerGroup,FarmerProfileDetailView, EditFarmerGroup)
from rest_framework.urlpatterns import format_suffix_patterns



router = routers.DefaultRouter()
router.register(r'groups', views.GroupViewSet)
router.register(r'farmerprofiles', views.FarmerProfileViewSet, basename='FarmerProfile')

approve_farmer= FarmerProfileViewSet.as_view({
    'patch': 'approved',
    'get': 'retrieve',
    'put': 'decline',
    'delete': 'destroy',
    'get':'list',
    'post':'create'

})
# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.

app_name = 'farmer'
urlpatterns = [
    path('api/', include(router.urls)),
    path('groups', GroupList.as_view(), name='group_list'),
    path('create/group', CreateFarmerGroup.as_view(), name="create_farmer_group"),
    path('group/<int:pk>/edit', EditFarmerGroup.as_view(), name="edit_farmer_group"),
    path('farmerprofile', FarmerProfileList.as_view(), name='farmerprofile_list'),
    path('create/profile', CreateFarmerProfile.as_view(), name="create_farmer"),
    path('<int:pk>/edit/', UpdateFarmerProfile.as_view(), name="edit_farmer_profile"),
    path('<int:pk>/approve/', approve_farmer, name='approve'),

    path('<int:pk>/view/', FarmerProfileDetailView.as_view(), name="view_farmer_profile"),

    path('columnchart/', views.farmer_class_view, name ="column_chart")

]

ict4farmers/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from common .views import LoginView, LogoutView
from django.conf.urls.static import static
from django.conf import settings
from common.views import obtain_auth_token 
from rest_framework_swagger.views import get_swagger_view
schema_view = get_swagger_view(title="ICT4Farmers API Docs")

urlpatterns = [
    path('admin/', admin.site.urls),
    # api documentation
    path('api/docs', schema_view),
    # authentication urls
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # api authentication urls
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),

    # common urls
    path('', include('common.urls', namespace="common")),

    # open market urls
    path('openmarket/', include('openmarket.urls', namespace="openmarket")),

    # farm urls
  
    path('farm/', include('farm.urls', namespace="farm")),

    # farmer urls
   
    path('farmer/', include('farmer.urls', namespace="farmer")),

    # unffeagents urls
    path('unffeagents/', include('unffeagents.urls', namespace="unffeagents")),

    # open weather urls
   
    path('weather/', include('weather.urls', namespace="weather")),

    # resorce sharing urls
    path('resourcesharing/', include('resourcesharing.urls', namespace="resourcesharing")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urls.py
from django.urls import path
from apis.views import ( api_house_detail_view, api_house_detail_update)

app_name = 'landlord'

urlpatterns = [
    path('house/<int:id>/', api_house_detail_view, name="house-api"),
    path('house/update/<int:id>', api_house_detail_view, name="house-api")
    ,]

farmer/models.py
from django.db import models
from django.contrib.auth.models import User
from common.models import(Region, District, County, SubCounty, Parish, Village, TimeStampedModel)
from common.choices import(GENDER_CHOICES, MARITAL_STATUSES,STATUS, LAND_TYPES, SCALE, YES_OR_NO,EDUCATION_LEVEL)
import phonenumbers
from phonenumber_field.modelfields import PhoneNumberField
from django.utils.translation import ugettext as _
from farm .models import Sector

# Create your models here.

class Group(TimeStampedModel, models.Model):
    name = models.CharField(_('Group Name'), max_length=100, null=False, blank=False)
    description = models.TextField(blank=True, null=True)
    logo = models.ImageField(null=True)
    address = models.TextField(blank=False, null=False)
    contact_person = models.CharField(max_length=100)
    contact_person_email = models.EmailField(null=True)
    contact_person_phone = PhoneNumberField(blank=False, null=False)

    def __str__(self):
        return self.name


class FarmerProfile(TimeStampedModel, models.Model):
    CREDIT = (
        (None, '--please select--'),
        ('SACCO', 'SACCO'),
        ('Village Savings and Loan Associate', 'Village Savings and Loan Associate'),
        ('Bank', 'Bank'),
        ('Farmer Groups', 'Farmer Groups'),
     )

    user = models.OneToOneField(User, on_delete=models.CASCADE, unique=True, related_name='farmer',primary_key=True)
    # personal information

    nin = models.CharField(_('National Identity Number (NIN)'),max_length=14, null=False, blank=False)
    level_of_education = models.CharField(choices = EDUCATION_LEVEL, max_length=100, null=False, blank=False)
    marital_status = models.CharField(choices=MARITAL_STATUSES, max_length=15, null=False, blank=False)
    number_of_dependants = models.PositiveIntegerField()
    credit_access = models.BooleanField(_('Have access to credit ?.'), choices=YES_OR_NO, null=True, blank=False)
    source_of_credit = models.CharField(choices=CREDIT, max_length=50, null=True, blank=False, default=False)
    experience = models.FloatField(_('Farming Experience in years'),null=False, blank=False)
    occupation = models.CharField(max_length=100, null=True, blank=False)
    # farming information
    sector = models.ManyToManyField(Sector, related_name='farmer_sectors')
    group = models.ForeignKey(Group, on_delete=models.DO_NOTHING, null=True, blank=True)
    size_of_land = models.DecimalField(_('Size of land in acres') ,decimal_places=2, max_digits=20, blank=False)
    type_of_land = models.CharField(choices=LAND_TYPES, max_length=20)
    production_scale = models.CharField(choices=SCALE, max_length=50)
    general_remarks = models.TextField(null=True, blank=True)
    # initial capital moved to farm
    #initial_total_capital = models.DecimalField(decimal_places=2, max_digits=20, blank=False)

    status = models.CharField(choices=STATUS, default='Pending', max_length=20,null=False)
    # handle approving of a farmer
    approver = models.ForeignKey(User, on_delete=models.DO_NOTHING,related_name="unffe_agent",null=True,blank=True)
    approved_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return str(self.user.last_name)



    class Meta:
        permissions = (
            ("can_approve_farmers", "Can approve farmers"),
        )

farmer/forms.py
from django import forms
from .models import FarmerProfile, Group
from phonenumber_field.formfields import PhoneNumberField
from phonenumber_field.widgets import PhoneNumberPrefixWidget
from common .models import(District, County, SubCounty, Parish, Village)
from common .choices import PAST_YEARS


class FarmerProfileForm(forms.ModelForm):
   # date_of_birth = forms.DateField(widget=forms.SelectDateWidget(years=PAST_YEARS,attrs={'class': 'form-control','style':'display:inline-block; width:33%; '}))
   


    class Meta:
        model = FarmerProfile
        exclude = ['user','status','approver','approved_date']

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(FarmerProfileForm, self).__init__(*args, **kwargs)
        self.fields['general_remarks'].widget.attrs.update({'rows': '2'})
        self.fields['group'].empty_label = None
       
      

class FarmerGroupForm(forms.ModelForm):

    contact_person_phone = PhoneNumberField(widget=PhoneNumberPrefixWidget(attrs={'class': 'form-control','style': 'width:50%; display:inline-block;'}), required=True, initial='+256')


    class Meta:
        model = Group
        exclude = []

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(FarmerGroupForm, self).__init__(*args, **kwargs)
        self.fields['description'].widget.attrs.update({'rows': '2'})
        self.fields['address'].widget.attrs.update({'rows': '2'})
            

farmer/templates/create_farmer_profile.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'css/multi_form.css' %}">
            <!-- Container-fluid starts-->
            <div class="container-fluid">
                <div class="page-header">
                    <div class="row">
                        <div class="col">
                            <div class="page-header-left">
                                <h3>{% if farmerprofile %} Edit {% else %}Create {% endif %} Farmer Profile
                                   
                                </h3>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <ol class="breadcrumb float-right">
                                <li class="breadcrumb-item"><a href="{% url 'common:home' %}"><i data-feather="home"></i></a></li>
                                <li class="breadcrumb-item">Farmers </li>
                                <li class="breadcrumb-item active">Add Profile </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Container-fluid Ends-->

            <!-- Container-fluid starts-->
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="card tab2-card ">
                            <div class="card-header">
                                <h5> {% if farmerprofile %} Update {% else %} Add {% endif %}Farmer Profile</h5>
                            </div>
                            <form method="POST"  id="form"  data-districts-url="{% url 'common:ajax_load_districts' %}" novalidate enctype="multipart/form-data" class="card-body"
                            data-counties-url="{% url 'common:ajax_load_counties' %}"
                            data-sub_counties-url="{% url 'common:ajax_load_sub_counties' %}"
                            data-parishes-url="{% url 'common:ajax_load_parishes' %}"
                            data-villages-url="{% url 'common:ajax_load_villages' %}">
                                {% csrf_token %}
 
                                <div class="tab-content" id="myTabContent">
                                    <div class="tab" id="personalinfo" role="tabpanel" aria-labelledby="personalinfo-tab">
                                        <div class="row">
                                            <div class="col-md-12">
                                                <h4>Personal Information</h4>
                                          </div>
                                            <div class="col-xl-12 col-md-12">
                                                {{ form.nin|as_crispy_field }}
                                            </div>
                                           
                                            <div class="col-xl-6 col-md-6">
                                                {{ form.level_of_education|as_crispy_field }}
                                            </div>
                                            <div class="col-xl-6 col-md-6">
                                                {{ form.marital_status|as_crispy_field }}
                                            </div>
                                            <div class="col-md-6">
                                                {{ form.occupation|as_crispy_field }}
                                            </div>
                                            <div class="col-md-6">
                                                {{ form.number_of_dependants|as_crispy_field }}
                                            </div>
                                            <div class="col-md-6">
                                                {{ form.credit_access|as_crispy_field }}
                                            </div>
                                            <div class="col-md-6" id="credit_source">
                                                {{ form.source_of_credit|as_crispy_field }}
                                            </div>
                                            <div class="col-md-6">
                                                {{ form.experience|as_crispy_field }}
                                            </div>
                                        </div>
                                    </div>
                
                                    <div class="tab" id="farming" role="tabpanel" aria-labelledby="farming-tabs">
                                       
                                          
                                        <div class="row">
                                            <div class="col-md-12">
                                                <h4>Farming Information</h4>
                                          </div>
                                          
                                            <div class="col-md-6">
                                                {{ form.sector|as_crispy_field }} 
                                            </div>
                                            <div class="col-md-6">
                                                {{ form.group|as_crispy_field }}
                                            </div>
                                            <div class="col-xl-4 col-md-4">
                                                {{ form.size_of_land|as_crispy_field }}
                                            </div>
                                            <div class="col-xl-4 col-md-4">
                                                {{ form.type_of_land|as_crispy_field }}
                                            </div>
                                            <div class="col-xl-4 col-md-4">
                                                {{ form.production_scale|as_crispy_field }}
                                            </div>
                                            <div class="col-xl-12 col-md-12">
                                                {{ form.general_remarks|as_crispy_field }}
                                            </div>
                                        
                                        </div>
                                  
                                </div>
                                </div>
                                <div style="overflow:auto;">
                                    <div style="float:right;">
                                      <button type="button" class="btn previous">Previous</button>
                                        <button type="button" class="next btn btn-primary">Next</button>
                                       
                                        <button type="button" class="btn btn-primary submit">Submit</button>
                                    </div>
                                </div>
                                <!-- Circles which indicates the steps of the form: -->
                                <div style="text-align:center;margin-top:40px;">
                                    <span class="step">1</span>
                                    <span class="step">2</span>
                                    
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Container-fluid Ends-->
            {% endblock %}
           

<!--select 2-->
<!-- latest jquery-->
{% block javascript %}
 <!-- included them for stepwise forms  -->

<script>

    $(document).ready(function () {
      // add select 2 to dropdown fields
      $('#id_sector').select2( );
      $('#id_group').select2();
      $('#credit_source').hide();  
     
      $('#div_id_credit_access').change(function () {

        if ($('#id_credit_access').val() == 'True') {
            $('#credit_source').show();
        }
        else if ($('#id_credit_access').val() == 'False') {
            $('#credit_source').hide();
        }

        })


            var val = {
                // Specify validation rules
                rules: {
                  phone_1_1: {
                        required: true,
                        minlength:9,
                        digits: true
                    },
                    phone_2_1: {
                      required: true,
                        minlength:9,
                        digits: true

                    },
                    nin: {
                        required: true,
                        
                    }
                },
                // Specify validation error messages
                messages: {
                  phone_1_1:
                        "Please enter a valid phone number",
                   phone_2_1: {
                        required: "Please enter a valid phone numbe"
                    },
                    nin: {
                        required: "Please a valid NIN"
                    }
                }
            }
    // calling multistep 
    $("#form").multiStepForm(
                {
                    // defaultStep:0,
                    beforeSubmit: function (form, submit) {
                        console.log("called before submiting the form");
                        console.log(form);
                        console.log(submit);
                    },
                    validations: val,
                }
            ).navigateTo(0);



    });
  
  
  </script>
{% endblock %}

farmer/templates/credit.html
<!-- <p>{{data}}</p>
<p>{{labels}}</p> -->

{% block content %}
  <div id="container" style="width: 35%;">
    <canvas id="pie-chart"></canvas>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
  <script>

    var config = {
      type: 'pie',
      data: {
        datasets: [{
          data: {{ data|safe }},
          backgroundColor: [
            '#00BFFF', 'red', 'green', 'blue'
          ],
          label: 'Population'
        }],
        labels: {{ labels|safe }}
      },
      options: {
        responsive: true
      }
    };

    window.onload = function() {
      var ctx = document.getElementById('pie-chart').getContext('2d');
      window.myPie = new Chart(ctx, config);
    };

  </script>

{% endblock %}

farmer/templates/farmerprofile_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
   <!-- Container-fluid starts-->
   <div class="container-fluid">
    <div class="page-header">
        <div class="row">
            <div class="col-lg-6">
                <div class="page-header-left">
                    <h3>Farmer profile List <br>
                      {% if request.user.is_superuser or perms.farmer.add_farmerprofile %}
                      <small><a class="add-new" href="{% url 'farmer:create_farmer' %}">
                        {% if request.user.is_superuser %}
                        Add new
                        {% else %}
                        Register
                        {% endif %}
                      </a></small>
                      {% endif %}
                    </h3>
                </div>
            </div>
            <div class="col-lg-6">
                <ol class="breadcrumb float-right">
                    <li class="breadcrumb-item"><a href="{% url 'common:home' %}"><i data-feather="home"></i></a></li>
                    <li class="breadcrumb-item">Farmer profile</li>
                    <li class="breadcrumb-item active">Farmer profile List</li>
                </ol>
            </div>
        </div>
    </div>
</div>

<!-- Container-fluid Ends-->



<!-- bootstrap table begin here -->
<div id="toolbar">
  {% if request.user.is_superuser or perms.farmer.delete_farmerprofile %}
  <button id="remove" class="btn btn-danger" title="Delete" disabled>
    <i class="fa fa-trash"></i>
  </button>

  {% endif %}
  {% if request.user.is_superuser or perms.farmer.can_approve_farmers %}
  <button id="decline" class="btn btn-decline" title="Decline" disabled>
    <i class="fa fa-times"></i>
  </button>
  <button id="approve" class="btn btn-primary" title="Approve" disabled>
    <i class="fa fa-check"></i>
  </button>
  {% endif %}
</div>
<table
  id="table"
  data-toggle="table"
  data-show-toggle="true"
  data-search="true"
  data-show-search-button="true"
  data-show-refresh="true"
  data-show-fullscreen="true"
  data-show-columns="true"
  data-show-columns-toggle-all="true"
  data-show-export="true"
  data-click-to-select="true"
  data-minimum-count-columns="2"
  data-show-pagination-switch="true"
  data-pagination="true"
  data-id-field="user_id"
  data-total-field="count"
  data-data-field="results"
  data-toolbar="#toolbar"
  data-side-pagination="server"
  data-server-sort="false"
  data-export-types="[‘png’, ‘csv’,‘doc’, ‘excel’, ‘xlsx’, ‘pdf’]"
  data-page-list="[10, 25, 50, 100, all]"
  data-url="/farmer/api/farmerprofiles/?format=json"
  data-response-handler="responseHandler">
  <thead>
    <tr>
      {% if request.user.is_superuser or perms.farmer.delete_farmerprofile %}
      <th data-field="state" data-checkbox="true"></th>
      {% endif %}
      <th data-field="full_name" data-sortable="true">Name</th>
      <th data-field="date_of_birth" data-visible="false"  data-sortable="true">DOB</th>
      <th data-field="nin" data-visible="false"  data-sortable="true">NIN</th>
      <th data-field="sector" data-sortable="true">Sector</th>
      <th data-field="region" data-sortable="true">Region</th>
      <th data-field="district" data-sortable="true">District</th>
      <th data-field="county" data-visible="false" data-sortable="true">County</th>
      <th data-field="sub_county" data-visible="false" data-sortable="true">Sub County</th>
      <th data-field="parish" data-visible="false" data-sortable="true">Parish</th>
      <th data-field="village" data-visible="false" data-sortable="true">Village</th>
      <th data-field="level_of_education" data-visible="false"  data-sortable="true">Education Level</th>
      <th data-field="marital_status" data-visible="false" data-sortable="true">Marital Status</th>
      <th data-field="size_of_land" data-visible="false"  data-sortable="true">Size of Land</th>
      <th data-field="phone_1" data-sortable="true">Phone</th>
      <th data-field="phone_2" data-visible="false" data-sortable="true">Phone 2</th>
      <th data-field="group" data-sortable="true">Group</th>
      <th data-field="type_of_land" data-visible="false" data-sortable="true">Land Type</th>
      <th data-field="production_scale" data-visible="false"  data-sortable="true">Production Scale</th>
      <th data-field="number_of_dependants" data-visible="false" data-sortable="true">Number of Dependants</th>
      <th data-field="credit_access" data-visible="false" data-sortable="true">Access to Credit</th>
      <th data-field="source_of_credit" data-visible="false" data-sortable="true">Source of Credit</th>
      <th data-field="experience" data-visible="false"  data-sortable="true">experience</th>
      <th data-field="status" data-sortable="true">status</th>
      <th data-formatter="operateFormatter"  class="text-center">Action</th>
      
    </tr>
  </thead>
</table>
 <!--bootstrap table ends here-->

 {% endblock %}

<!-- latest jquery-->
{% block javascript %}
<script>
  var $table = $('#table')
  var $remove = $('#remove')
  var $approve = $('#approve')
  var $decline = $('#decline')
  var selections = []

  function getIdSelections() {
    return $.map($table.bootstrapTable('getSelections'), function (row) {
      return row.user_id
    })
  }

  function responseHandler(res) {
    $.each(res.rows, function (i, row) {
      row.state = $.inArray(row.user_id, selections) !== -1
    })
    return res
  }



  function operateFormatter(value, row, index) {
    var url ="/farmer/"+row.user_id+"/edit"
    var view_url ="/farmer/"+row.user_id+"/view"
    return [
    {% if request.user.is_superuser or perms.farmer.change_farmerprofile %}
      '<a class="Edit " href="'+url+'" title="Update">',
      '<i class="fa fa-edit"></i>',
      '</a>  ',
        {% endif %}
        {% if request.user.is_superuser or perms.farmer.view_farmerprofile %}
        '<a class="Edit " href="'+view_url+'" title="De"tails>',
      '<i class="fa fa-eye"></i>',
      '</a>  ',
      {% endif %}
    ].join('')
  }


  ///used cookies to get crsf token
  function getCookie(c_name)
    {
      if (document.cookie.length > 0)
        {
          c_start = document.cookie.indexOf(c_name + "=");
            if (c_start != -1)
         {
            c_start = c_start + c_name.length + 1;
            c_end = document.cookie.indexOf(";", c_start);
            if (c_end == -1) c_end = document.cookie.length;
            return unescape(document.cookie.substring(c_start,c_end));
         }
     }
      return "";
   }

  function initTable() {

    $table.on('check.bs.table uncheck.bs.table ' +
      'check-all.bs.table uncheck-all.bs.table',
    function () {
      $remove.prop('disabled', !$table.bootstrapTable('getSelections').length)
      $approve.prop('disabled', !$table.bootstrapTable('getSelections').length)
      $decline.prop('disabled', !$table.bootstrapTable('getSelections').length)

      // save your data, here just save the current page
      selections = getIdSelections()
      // push or splice the selections if you want to save all data selections
    })
    $table.on('all.bs.table', function (e, name, args) {
      console.log(name, args)
    })
    ///multiple delete
    $remove.click(function () {
      var ids = getIdSelections()
      $remove.prop('disabled', true)

      swal({
  title: "Are you sure?",
  text: "Once deleted, you will not be able to recover these records!",
  icon: "warning",
  buttons: true,
  dangerMode: true,
})
.then((willDelete) => {
  if (willDelete) {
    for(id=0; id<ids.length; id++){
        console.log(ids[id]);

    $.ajax({
        url: "/farmer/api/farmerprofiles/"+ids[id],
        data: {},
        headers:{"X-CSRFToken": getCookie("csrftoken")},
        type: 'DELETE',
        contentType: 'application/json',
        success: function(result) {
          console.log('deleted successfule');
        },
       });
    swal("Your record/s have been deleted successfully!", {
      icon: "success",
    }).then(() =>{
        window.location.reload()});
    }
  } else {
    swal("You have cancelled the deletion of records!");
  }
});

    })

    ///approve farmer profiles
    $approve.click(function () {
      var ids = getIdSelections()
      $approve.prop('disabled', true)

      swal({
  title: "Approve Farmer Applications?",
  text: "Are you sure you want to approve these applications!",
  icon: "success",
  buttons: true,
  dangerMode: false,
})
.then((willDelete) => {
  if (willDelete) {
    for(id=0; id<ids.length; id++){
        console.log(ids[id]);

    $.ajax({
        url: "/farmer/"+ids[id]+'/approve/',
        data: {},
        headers:{"X-CSRFToken": getCookie("csrftoken")},
        type: 'PATCH',
        //contentType: 'application/json',
        success: function(result) {
          console.log('approved successfully');
        },
       });
    swal("You have approve farmer/s successfully!", {
      icon: "success",
    }).then(() =>{
        window.location.reload()});
    }
  } else {
    swal("You have cancelled farmer approvals!");
  }
});

    })


    ///decline farmer request
    $decline.click(function () {
      var ids = getIdSelections()
      $decline.prop('disabled', true)

      swal({
  title: "Decline Application",
  text: "Are you sure You want to decline these Applications?",
  icon: "warning",
  buttons: true,
  dangerMode: false,
})
.then((willDelete) => {
  if (willDelete) {
    for(id=0; id<ids.length; id++){
        console.log(ids[id]);

    $.ajax({
        url: "/farmer/"+ids[id]+'/approve/',
        data: {},
        headers:{"X-CSRFToken": getCookie("csrftoken")},
        type: 'PUT',
        //contentType: 'application/json',
        success: function(result) {
          console.log('approved successfully');
        },
       });
    swal("You have declined farmer/s successfully!", {
      icon: "success",
    }).then(() =>{
        window.location.reload()});
    }
  } else {
    swal("You have cancelled farmer approvals!");
  }
});

    })

  }

  $(function() {
    initTable()

    $('#locale').change(initTable)
  })


</script>
{% endblock %}