farm/urls.py
from django.urls import include, path
from rest_framework import routers
from . import views
from .views import (SectorList, SectorDetail, CreateSector,EnterpriseList, FarmListView, FarmViewSet, 
CreateFarmView, EditFarmView,FarmproductionRecordsList,FarmproductionRecordsList,CreateFarmProductionRecordView,FarmMapViewSet,CreateEnterpriseView,EditEnterpriseView,CreateQueryView,
FarmProfileDetailView,QueryList,CreateFarmRecordView, FarmRecordsList, EditFarmRecordView,
CreateFarmFinancialRecordView,EditFarmproductionRecordView, EditFarmFinancialRecordView, FarmFinancilRecordsList,EditQueryView, EnterpriseSelectionView,
EnterpriseSelectionRedirect,EnterpriseSelectionDetailView)


router = routers.DefaultRouter()

router.register(r'farms', views.FarmViewSet,'farm-api')
router.register(r'maps', views.FarmMapViewSet,'maps-api')
router.register(r'sector', views.SectorViewSet,'apisector')
router.register(r'enterpriseselection', views.EnterpriseSelectionViewSet,'api-enterpriseselection' )
router.register(r'enterprise', views.EnterpriseViewSet, basename='Enterprise')
router.register(r'farmrecords', views.FarmRecordViewSet, basename='FarmRecord')
router.register(r'financialrecords',views.FarmFinancialRecordViewSet,'FinancialRecord')
router.register(r'productionrecords',views.FarmProductionRecordViewSet,'ProductionRecord')
router.register(r'query', views.QueryViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.

app_name = 'farm'
urlpatterns = [
    path('api/', include(router.urls)),
    path('list', FarmListView.as_view(), name='farm_list'),
    path('create', CreateFarmView.as_view(), name="create_farm"),
    path('sectors', SectorList.as_view(), name='sector_list'),
    path('<int:pk>/edit/farm', EditFarmView.as_view(), name="edit_farm"),
    path('<int:pk>/edit/sector', SectorDetail.as_view(), name="edit_sector"),
    path('create/sector', CreateSector.as_view(), name="create_sector"),
    path('create/query', CreateQueryView.as_view(), name="create_query"),
    path('<int:pk>/edit/query', EditQueryView.as_view(), name="edit_query"),
    path('queries', QueryList.as_view(), name='query_list'),
    path('enterprises', EnterpriseList.as_view(), name='enterprise_list'),
    path('create/enterprise/<int:farm_pk>', CreateEnterpriseView.as_view(), name="create_enterprise"),
    path('<int:pk>/edit/enterprise', EditEnterpriseView.as_view(), name="edit_enterprise"),
    path('<int:pk>/view/', FarmProfileDetailView.as_view(), name="view_farm_profile"),  
    path('create/record/<int:enterprise_pk>', CreateFarmRecordView.as_view(), name="create_farm_record"), 
    path('farmrecords', FarmRecordsList.as_view(), name='farmrecords') ,
    path('<int:pk>/edit/farmrecord', EditFarmRecordView.as_view(), name="edit_farmrecord"),
    path('create/financilrecord/<int:enterprise_pk>', CreateFarmFinancialRecordView.as_view(), name="create_financial_record"), 
    path('financialrecords', FarmFinancilRecordsList.as_view(), name='financialrecords') ,
    path('<int:pk>/edit/financialrecord', EditFarmFinancialRecordView.as_view(), name="edit_financail_record"),
    path('create/productionrecord/<int:enterprise_pk>', CreateFarmProductionRecordView.as_view(), name="create_production_record"), 
    path('productionrecords', FarmproductionRecordsList.as_view(), name='productionrecords') ,
    path('<int:pk>/edit/productionrecord', EditFarmproductionRecordView.as_view(), name="edit_production_record"),
    path('create/enterpriseselection', EnterpriseSelectionView.as_view(), name='enterprise_selection'),
    path('selectenterprises', EnterpriseSelectionRedirect.as_view(), name='select_enterpise'),
    path('<int:pk>/view/selectenterprise', EnterpriseSelectionDetailView.as_view(), name="view_enterprise_selection"),
    #path('viewselectenterprises', EnterpriseSelectionDetailView.as_view(), name='enterprise_selection_detail'),
]

ict4farmers/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from common .views import LoginView, LogoutView
from django.conf.urls.static import static
from django.conf import settings
from common.views import obtain_auth_token 
from rest_framework_swagger.views import get_swagger_view
schema_view = get_swagger_view(title="ICT4Farmers API Docs")

urlpatterns = [
    path('admin/', admin.site.urls),
    # api documentation
    path('api/docs', schema_view),
    # authentication urls
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # api authentication urls
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),

    # common urls
    path('', include('common.urls', namespace="common")),

    # open market urls
    path('openmarket/', include('openmarket.urls', namespace="openmarket")),

    # farm urls
  
    path('farm/', include('farm.urls', namespace="farm")),

    # farmer urls
   
    path('farmer/', include('farmer.urls', namespace="farmer")),

    # unffeagents urls
    path('unffeagents/', include('unffeagents.urls', namespace="unffeagents")),

    # open weather urls
   
    path('weather/', include('weather.urls', namespace="weather")),

    # resorce sharing urls
    path('resourcesharing/', include('resourcesharing.urls', namespace="resourcesharing")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urls.py
from django.urls import path
from apis.views import ( api_house_detail_view, api_house_detail_update)

app_name = 'landlord'

urlpatterns = [
    path('house/<int:id>/', api_house_detail_view, name="house-api"),
    path('house/update/<int:id>', api_house_detail_view, name="house-api")
    ,]

farm/models.py
from django.db import models
from django.utils.translation import ugettext as _
from common .models import(TimeStampedModel,District,Region)
from django.contrib.auth.models import User
from common .choices import (TRANSACTION_TYPE,PAYMENT_OPTIONS, PAYMENT_MODE,YES_OR_NO,QUERIES, SCALE,SECTOR,
PROFESSION, EDUCATION_LEVEL,INCOME, UNIT, CAPITAL)
from geopy.geocoders import Nominatim
import phonenumbers
from phonenumber_field.modelfields import PhoneNumberField
from django_postgres_extensions.models.fields import ArrayField
from django.contrib.gis.db import models
from geopy.geocoders import Nominatim



# Create your models here.


class Sector(TimeStampedModel, models.Model):

    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name


class Farm(TimeStampedModel, models.Model):
    FARM_STATUS = (
        (None, '--please select--'),
        ('active', 'Active'),
        ('closed', 'Closed')
     )
    farm_name = models.CharField(max_length=100, null=False, blank=False)
    farmer = models.ForeignKey('farmer.FarmerProfile', on_delete=models.CASCADE, related_name='farms')
    location = models.PointField( srid=4326,null=True)
    start_date = models.DateField(blank=False, null=False)
    close_date = models.DateField(blank=True, null=True)
    image = models.ImageField(null=True, blank=False)
    status = models.CharField(_('Farm Status'), default='active', max_length=20, choices=FARM_STATUS)
    general_remarks = models.TextField(null=True, blank=True)
    availability_of_services = models.BooleanField(_('Have access to Services ?.'), choices=YES_OR_NO, null=False, blank=False, default=True)
    availability_of_water = models.BooleanField(_('Does a the farm have a water source ?.'), choices=YES_OR_NO, null=False, blank=False, default=True)
    land_occupied = models.FloatField( _('Amount of land occupied(acres)'), blank=False, null=True)
    available_land = models.FloatField( _('Size of land Available'), blank=True, null=True)

    def __str__(self):
        return self.farm_name

    @property
    def compute_location(self):
        geolocator = Nominatim(user_agent="ICT4Farmers", timeout=10)
       
       
        try:
            lat = str(self.location.x)
            lon = str(self.location.y)
            location = geolocator.reverse(lat + "," + lon)
            return '{}'.format(location.address)
        except:
            # location = str(self.location.y) + "," + str(self.location.x)
            return 'slow network, loading location ...'



class EnterpriseType(TimeStampedModel, models.Model):

    name = models.CharField(max_length=50, null=False, blank=False)
    sector = models.ForeignKey(Sector, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name



class Enterprise(TimeStampedModel, models.Model):
    Enterprise_STATUS = (
        (None, '--please select--'),
        ('open', 'Open'),
        ('closed', 'Closed')
     )
    name = models.CharField(_('Enterprise Name'), max_length=50, null=False, blank=False)
    farm = models.ForeignKey(Farm, on_delete=models.CASCADE, null=True, related_name='enterprises')
    sector = models.ForeignKey(Sector, on_delete=models.CASCADE, null=True, blank=False)
    source = models.CharField(_('Source(Operation wealth creation, etc)'),blank=False, null=True, max_length=200)
    enterprise_type = models.CharField(blank=False, null=True, max_length=200)
    animal_seed_density = models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of animals/seedling per enterprise in a particular period of time.')
    capital_invested = models.DecimalField(decimal_places=2, max_digits=1000, null=True)
    return_on_investment = models.DecimalField(_('Expected Return on Investment'), decimal_places=2, max_digits=1000, null=True)
    from_period = models.DateField(blank=False, null=True)
    to_period = models.DateField(blank=False, null=True)
    land_occupied = models.FloatField( blank=False, null=True)
    start_date = models.DateField(_('Farm Start Date'), blank=False, null=True)
    close_date = models.DateField(blank=True, null=True)
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(null=True, blank=False)
    status = models.CharField(_('Enterprise Status'), default='active', max_length=20, choices=Enterprise_STATUS)


    def __str__(self):
        return self.name



class FarmFacility(TimeStampedModel, models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)
    farm = models.ForeignKey(Farm, on_delete=models.DO_NOTHING, related_name='facilities')
    description = models.TextField( blank=True, null=True)
    image = models.ImageField()

    def __str__(self):
        return self.name

'''
These are farm products
'''
class Produce(TimeStampedModel, models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)
    description = models.TextField( blank=True, null=True)
    quantity = models.DecimalField(decimal_places=2, max_digits=20, blank=False)

    def __str__(self):
        return self.name


class FarmProduce(TimeStampedModel, models.Model):
    enterprise = models.ForeignKey(Enterprise, on_delete=models.DO_NOTHING, null=False, blank=False, related_name='farm_produces')
    produce = models.ForeignKey(Produce, on_delete=models.DO_NOTHING)
    quantity = models.FloatField(blank=False, null=False)
    description = models.TextField( blank=True, null=True)
    production_date = models.DateField()
    taken_by = models.CharField(max_length=100, null=True, blank=True)
    reported_by = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.produce)


class FinancialRecord(TimeStampedModel, models.Model):
    FINANCIAL_OPTIONS = (
    (None, '--please select--'),
    ('full_payment', 'Full Payment'),
    ('installments', 'Installments'),
    ('debt', 'Debt')
    )
    enterprise = models.ForeignKey(Enterprise, on_delete=models.DO_NOTHING, null=False, blank=False, related_name='farm_financial_record')
    transaction_type = models.CharField(choices=TRANSACTION_TYPE, max_length=100, null=False)
    payment_mode = models.CharField(choices=FINANCIAL_OPTIONS, max_length=100, null=True)
    next_payment_date = models.DateField(null=True, blank=True)
    transaction_date = models.DateField(auto_now=True)
    spent_on = models.CharField(_('Payment for'),max_length=200)
    transaction_to = models.CharField(_('Payment To/From'),max_length=100)
    amount = models.FloatField(_('Amount paid'),blank=False, null=False)
    quantity = models.FloatField()
    means_of_payment = models.CharField(max_length=20, blank=False, null=False, choices=PAYMENT_MODE)
    transaction_date = models.DateField(auto_now=True)
    description = models.TextField( blank=True, null=True)
    reported_by = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.spent_on



class ProductionRecord(TimeStampedModel, models.Model):
    enterprise = models.ForeignKey(Enterprise, on_delete=models.DO_NOTHING, null=False, blank=False, related_name='farm_production_record')
    record_name = models.CharField(max_length=25, null=True, blank=True)
    production_activity = models.CharField(max_length=50, null=True, blank=True)
    quantity = models.DecimalField(decimal_places=2, max_digits=20, blank=False)
    unit_of_measure =  models.CharField(choices=UNIT, max_length=25, null=True, blank=False)
    #measurements = models.CharField(max_length=25, null=True, blank=True)
    record_date = models.DateField()
    record_time = models.TimeField(auto_now=True, blank=True)
    record_taker = models.CharField(max_length=50, null=True, blank=True)
    general_remarks = models.TextField(max_length=150, null=True, blank=True)

    def __str__(self):
        return self.record_name

class Query(TimeStampedModel, models.Model):
    QUERY_TYPES = (
        (None, '--please select--'),
        ('extentional_reports', 'Extentional Report'),
        ('others', 'Others')
     )
    query_type = models.CharField(choices=QUERY_TYPES, max_length=25, null=True, blank=False)
    query_category = models.CharField(choices=QUERIES, max_length=25, null=True, blank=True)
    farm = models.ForeignKey(Farm, on_delete=models.DO_NOTHING, null=False, blank=False, related_name='farm_pests_and_diseases')
    name = models.CharField(_('Extension Workers Name'),max_length=50, null=True, blank=True)
    description = models.TextField( blank=True, null=True)
    date_discovered = models.DateField(null=True, blank=True)
    action_taken = models.TextField( blank=False, null=True)
    image = models.ImageField(null=True, blank=False)
    reporting_date = models.DateField(auto_now=True)
    solution = models.TextField( blank=True, null=True)


    def __str__(self):
        return self.query_category


class RecordType(models.Model):
    name = models.CharField(max_length=100,null=False,blank=False)

    def __str__(self):
        return self.name


class FarmRecord(TimeStampedModel, models.Model):

    enterprise = models.ForeignKey(Enterprise, on_delete=models.DO_NOTHING, null=True, blank=False, related_name='farm_records')
    name = models.CharField(_('Activity'),max_length=200, null=False, blank=False)
    from_date = models.DateField()
    to_date = models.DateField()
    description = models.TextField( blank=True, null=True)
    # person responsible
    taken_by = models.CharField(_('Taken by'), blank=False, null=True, max_length=100)
    contact =  PhoneNumberField(_('Phone number'), blank=False, null=True)
    next_activity_date = models.DateField(null=True, blank=True)
    #reported_by = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):
        return self.name


class Crop(models.Model):
    crop = models.CharField(max_length = 100, null= True, blank=False)
    benefits = models.CharField(max_length = 100, null=True, blank=True)

farm/templates/create_enterprise.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
{% load crispy_forms_tags %}

            <!-- Container-fluid starts-->
            <div class="container-fluid">
                <div class="page-header">
                    <div class="row">
                        <div class="col">
                            <div class="page-header-left">
                                <h3>Create Enterprise
                                </h3>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <ol class="breadcrumb float-right">
                                <li class="breadcrumb-item"><a href="{% url 'farm:enterprise_list' %}"><i data-feather="home"></i></a></li>
                                <li class="breadcrumb-item add-new">Farms</li>
                                <li class="breadcrumb-item active">Add Enterprise </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Container-fluid Ends-->

            <!-- Container-fluid starts-->
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="card tab2-card">
                            <div class="card-header">
                                <h5> Add Enterprise</h5>
                                {% if messages %}
                                <div class="alert alert-info alert-dismissible fade show" role="alert">
                                    {% for message in messages %}
                                    <strong>{{message}}</strong>
                                    {% endfor %}
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                      <span aria-hidden="true">&times;</span>
                                    </button>
                                  </div>
                                  {% endif %}
                            </div>
                            <form method="POST" id="enterprise_form"  novalidate enctype="multipart/form-data" class="card-body">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-xl-6 col-md-6">
                                        {{ form.sector|as_crispy_field }}
                                    </div> 
                                    <div class="col-xl-6 col-md-6">
                                        {{ form.source|as_crispy_field }}
                                    </div> 
                                    <div class="col-xl-6 col-md-6">
                                        {{ form.farm|as_crispy_field }}
                                    </div>
                                    <div class="col-xl-6 col-md-6">
                                        {{ form.name|as_crispy_field }}
                                    </div>
                                    <div class="col-xl-6 col-md-6">
                                        {{ form.enterprise_type|as_crispy_field }}
                                    </div>
                                     
                                    <div class="col-xl-6 col-md-6">
                                        <div class="form-group">
                                            <label for="land_occupied" class="required">Land occupied{% if form.land_occupied.field.required %}<span class="error"
                                                style="color:red">* ( Available farm land {{available_land}})</span>{% endif %}</label>
                                        {{form.land_occupied}}
                                        <span class="error" style="color:red" ><div id="land_occupied_error"></div>{{ form.land_occupied.errors }}</span>
                                    </div>
                                    </div>
                                    <div class="col-xl-6 col-md-6">
                                        {{ form.start_date|as_crispy_field }}
                                    </div>
                                    <div class="col-xl-6 col-md-6">
                                        {{ form.animal_seed_density|as_crispy_field }}
                                    </div>
                               
                                    <div class="col-xl-6 col-md-6">
                                        {{ form.capital_invested|as_crispy_field }}
                                    </div>
                                    <div class="col-xl-6 col-md-6">
                                        {{ form.return_on_investment|as_crispy_field }}
                                    </div>
                                    <div class="col-xl-6 col-md-6">
                                        {{ form.from_period|as_crispy_field }}
                                    </div>
                                    <div class="col-xl-6 col-md-4">
                                        {{ form.to_period|as_crispy_field }}
                                    </div>
                             
                                    <div class="col-xl-12 col-md-12">
                                        {{ form.description|as_crispy_field }}
                                    </div>
                                    <div class="col-xl-12 col-md-12">
                                        {{ form.image|as_crispy_field }}
                                    </div>
                                  
                                </div>
                              
                                <div class="float-right">
                                    <input type="submit" value="Submit" class="btn btn-primary">


                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Container-fluid Ends-->
            {% endblock %}
           

<!--select 2-->
<!-- latest jquery-->
{% block javascript %}
<!--select 2-->
<script type="text/javascript">

    $(document).ready(function () {


        $('#id_farm option:not(:selected)').attr('disabled', true);
        $("land_occupied_error").val("Enter a number less or equal to the available farm land");

        var available_farm_land = {{available_land}};
       
 $('#id_land_occupied').on('mouseleave', function(){
     var number_entered = $('#id_land_occupied').val();
     if(number_entered>available_farm_land){
         $("#land_occupied_error").text("Enter a number less or equal to the available farm land");
     }
     else if(number_entered <= available_farm_land){
        $("#land_occupied_error").text("");
     }


 })


    });
  
  
  </script>
{% endblock %}

farm/templates/create_sector.html
{% load rest_framework %}

<html>
    <body>

    <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
</head>

<div class="col-md-10 col-md-offset-1">
<h1>Sector - {{ sector.name }}</h1>

<form  action="{% url 'farm:create_sector' %}" method="post" novalidate>
    {% csrf_token %}
    {% render_form serializer template_pack='rest_framework/inline' %}
    <button type="submit" class="btn btn-default">Submit</button>
</form>
</div>
</body>
</html>

farm/templates/enterprise_email.html
{% extends 'root_email.html' %}
{% block heading %}
Dear {{ user.first_name }} {{user.last_name}},
{% endblock heading %}
{% block content_body %}

{{message}}
<br>

If you think, it's not you, then just ignore this email.
<br>
Kind Regards,<br>
ICT4Farmers Team
{% endblock content_body %}

farm/templates/enterprise_selection_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
   <!-- Container-fluid starts-->
   <div class="container-fluid">
    <div class="page-header">
        <div class="row">
            <div class="col-lg-6">
                <div class="page-header-left">
                    <h3>Enterprises Recommended
                      {% if request.user.is_superuser or perms.farm.add_enterpriseselection %}
                        <small><a class="add-new" href="{% url 'farm:enterprise_selection' %}">Add new</a></small>
                        {% endif %}
                    </h3>
                </div>
            </div>
            <div class="col-lg-6">
                <ol class="breadcrumb float-right">
                    <li class="breadcrumb-item"><a href="{% url 'common:home' %}"><i data-feather="home"></i></a></li>
                    <li class="breadcrumb-item">Enterprise Selection</li>
                    <li class="breadcrumb-item active"> Recommendations</li>
                </ol>
            </div>
        </div>
    </div>
</div>




<!-- bootstrap table begin here -->
<div id="toolbar">
  {% if request.user.is_superuser or perms.farm.delete_farm %}
  <button id="remove" class="btn btn-danger" disabled>
    <i class="fa fa-trash"></i> Delete
  </button>
  {% endif %}
</div>
<table
   id="table"
   data-toggle="table"
  data-show-toggle="true"
  data-search="true"
  data-show-search-button="true"
  data-show-refresh="true"
  data-show-fullscreen="true"
  data-show-columns="true"
  data-show-columns-toggle-all="true"
  data-show-export="true"
  data-click-to-select="true"
  data-minimum-count-columns="2"
  data-show-pagination-switch="true"
  data-pagination="true"
  data-id-field="id"
  data-total-field="count"
  data-data-field="results"
  data-toolbar="#toolbar"
  data-side-pagination="server"
  data-server-sort="false"
  data-page-list="[10, 25, 50, 100, all]"
  data-export-types="[‘png’, ‘csv’,‘doc’, ‘excel’, ‘xlsx’, ‘pdf’,'json']"
  data-url="/farm/api/enterpriseselection/"
  data-response-handler="responseHandler">
  <thead>
    <tr>
      {% if request.user.is_superuser or perms.farm.delete_enterpriseselection %}
      <th data-field="state" data-checkbox="true"></th>
      {% endif %}
      <th data-field="user" data-sortable="true">Name</th>
      <th data-field="profession" data-sortable="true">Profession</th>
      <th data-field="level_of_education" data-sortable="true">level of education</th>
      <th data-field="monthly_income" data-sortable="true">monthly Income</th>
      <th data-field="capital_available" data-visible="false" data-sortable="true">Capital To Invest</th>
      <th data-field="scale" data-sortable="true">Interested Production Scale</th>
      <th data-field="full_time_devotion"  data-visible="false" data-sortable="true">Full Time Farming</th>
      <th data-field="own_piece_of_land" data-sortable="true" >Do you own a piece of land</th>
      <th data-field="land_size" data-sortable="true" data-visible="false">Land Size</th>
      <th data-field="land_location" data-sortable="true" data-visible="false">Land Location</th>      
      <th data-field="what_is_your_inspiration_for_considering_in_farming" data-sortable="true" data-visible="false">Inspiration for considering farming</th>
      <th data-field="time_allocated_to_farming" data-sortable="true" data-visible="false">Time allocated to farming</th>
      <th data-field="crops" data-visible="true" data-sortable="true">Enterprises Recommended</th>
      <th data-formatter="operateFormatter"  class="text-center">Action</th>
                
    </tr>
  </thead>
</table>
 <!--bootstrap table ends here-->
 {% endblock %}
 {% block javascript %}
<script>
  var $table = $('#table');
  var $remove = $('#remove')
  var selections = []

  function getIdSelections() {
    return $.map($table.bootstrapTable('getSelections'), function (row) {
      return row.id
    })
  }
  function responseHandler(res) {
    $.each(res.rows, function (i, row) {
      row.state = $.inArray(row.id, selections) !== -1
    })
    return res
  }
  //displays an image
    function imageFormatter(value, row) {
      var url =row.image;
    return '<img class="img-thumbnail" src="'+url+'">'
  }
  function operateFormatter(value, row, index) {
    console.log(row.id);
    var url ="/farm/"+row.id+"/edit/farm";
    var view_url = "/farm/"+row.id+"/view/selectenterprise"
    var create_enterprise_url ="/farm/create/enterprise/"+row.id;
    return [
    // {% if request.user.is_superuser or perms.farm.change_farm %}
    //   '<a class="Edit " href="'+url+'" title="Edit">',
    //   '<i class="fa fa-pencil"></i>',
    //   '</a>  ',
    //     {% endif %}
    //     {% if request.user.is_superuser or perms.farm.add_enterprise %}
    //   '<a class="Edit " href="'+create_enterprise_url+'" title="Add Enterprise">',
    //   '<i class="fa fa-plus"></i>',
    //   '</a>  ',
    //     {% endif %}
        {% if request.user.is_superuser or perms.farm.view_enterpriseselection %}
        '<a class="Edit " href="'+view_url+'" title="View Recommended Enterprise">',
      '<i class="fa fa-eye"></i>',
      '</a>  ',
      {% endif %}
    ].join('')
  }

  ///used cookies to get crsf token
  function getCookie(c_name)
    {
      if (document.cookie.length > 0)
        {
          c_start = document.cookie.indexOf(c_name + "=");
            if (c_start != -1)
         {
            c_start = c_start + c_name.length + 1;
            c_end = document.cookie.indexOf(";", c_start);
            if (c_end == -1) c_end = document.cookie.length;
            return unescape(document.cookie.substring(c_start,c_end));
         }
     }
      return "";
   }
   function initTable() {

$table.on('check.bs.table uncheck.bs.table ' +
  'check-all.bs.table uncheck-all.bs.table',
function () {
  $remove.prop('disabled', !$table.bootstrapTable('getSelections').length)


  // save your data, here just save the current page
  selections = getIdSelections()
  // push or splice the selections if you want to save all data selections
})
$table.on('all.bs.table', function (e, name, args) {
  console.log(name, args)
})
///multiple delete
$remove.click(function () {
  var ids = getIdSelections()
  $remove.prop('disabled', true)

  swal({
title: "Are you sure?",
text: "Once deleted, you will not be able to recover these records!",
icon: "warning",
buttons: true,
dangerMode: true,
})
.then((willDelete) => {
if (willDelete) {
for(id=0; id<ids.length; id++){
    console.log(ids[id]);

$.ajax({
    url: "/farm/api/enterpriseselection/"+ids[id],
    data: {},
    headers:{"X-CSRFToken": getCookie("csrftoken")},
    type: 'DELETE',
    contentType: 'application/json',
    success: function(result) {
      console.log('deleted successfule');
    },
   });
swal("Your record/s have been deleted successfully!", {
  icon: "success",
}).then(() =>{
        window.location.reload()});
;}
} else {
swal("You have cancelled the deletion of records!");
}
});

})






}

$(function() {
initTable()

$('#locale').change(initTable)
})




</script>
 

 {% endblock %}

farm/templates/farm_created_successful_email.html
<p> Dear {{user.first_name}} {{user.last_name}}</p>
<p>{{message}}</p>