ict4farmers/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from common .views import LoginView, LogoutView
from django.conf.urls.static import static
from django.conf import settings
from common.views import obtain_auth_token 
from rest_framework_swagger.views import get_swagger_view
schema_view = get_swagger_view(title="ICT4Farmers API Docs")

urlpatterns = [
    path('admin/', admin.site.urls),
    # api documentation
    path('api/docs', schema_view),
    # authentication urls
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # api authentication urls
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),

    # common urls
    path('', include('common.urls', namespace="common")),

    # open market urls
    path('openmarket/', include('openmarket.urls', namespace="openmarket")),

    # farm urls
  
    path('farm/', include('farm.urls', namespace="farm")),

    # farmer urls
   
    path('farmer/', include('farmer.urls', namespace="farmer")),

    # unffeagents urls
    path('unffeagents/', include('unffeagents.urls', namespace="unffeagents")),

    # open weather urls
   
    path('weather/', include('weather.urls', namespace="weather")),

    # resorce sharing urls
    path('resourcesharing/', include('resourcesharing.urls', namespace="resourcesharing")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

openmarket/urls.py
from django.urls import include, path
from rest_framework import routers
from . import views
from .views import (ProductList,
                    SellerList,
                    MarketPriceList,
                    CreateBuyerPost,
                    CreateSellerProfile,
                    CreateProductProfile,
                    ServiceProviderList,
                    ServiceRegistrationList,
                    SellerPostList,
                    BuyerPostList,
                    ContactDetailsList,
                    LogiticsList,
                    SellerViewSet,
                    SoilScienceList,
                    ServiceProviderProfileList,
                    CreateServiceProviderProfile,
                    load_products,
                    CreateServiceView,
                    ServiceProviderViewSet,
                    UpdateServiceProviderProfile,
                    ServiceProviderProfileDetailView,
                    ServiceDetailView,
                    MapServiceDetailView,
                    EditServiceView,EditProductView,
                    EditSellerView,CreateSellerPost
                     )

router = routers.DefaultRouter()
router.register(r'products', views.ProductViewSet)
router.register(r'categories', views.CategoryViewSet)
router.register(r'sellers', views.SellerViewSet)
router.register(r'sellerposts', views.SellerPostViewSet, basename='sellerpost')
router.register(r'buyersposts', views.BuyerPostViewSet)
router.register(r'serviceproviders', views.ServiceProviderViewSet, basename='service_providers')

router.register(r'serviceregistration', views.ServiceRegistrationViewSet,  basename='services')

router.register(r'contactdetails', views.ContactDetailsViewSet)
router.register(r'logistics', views.LogisticsViewSet)
router.register(r'soilsciences', views.SoilScienceViewSet)
router.register(r'product_category',views.ProductCategoryViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API
# 

approve_serviceprovider= ServiceProviderViewSet.as_view({
    'patch': 'approved',
    'get': 'retrieve',
    'put': 'decline',
    'delete': 'destroy',
    'get':'list'})

approve_seller= SellerViewSet.as_view({
    'patch': 'approved',
    'get': 'retrieve',
    'put': 'decline',
    'delete': 'destroy',
    'get':'list',
    'post':'create'

})

app_name = 'openmarket'

urlpatterns = [
    path('api/', include(router.urls)),
    path('products', ProductList.as_view(), name='product_list'),
    
   
    path('create/products', CreateProductProfile.as_view(), name="create_product"),
    path('<int:pk>/edit/product/', EditProductView.as_view(), name="edit_product"),
    path('sellers', SellerList.as_view(), name='seller_list'),
    path('<int:pk>/approve/seller', approve_seller, name='approve_seller'),
    path('create/profile', CreateSellerProfile.as_view(), name="create_seller"),
    path('<int:pk>/edit/seller/', EditSellerView.as_view(), name="edit_seller"),
    path('sellerposts', SellerPostList.as_view(), name='sellerpost_list'),
    path('post/product',CreateSellerPost.as_view(), name='add_seller_post'),
    path('buyerposts', BuyerPostList.as_view(), name='buyerpost_list'),

    path('post/products',CreateBuyerPost.as_view(), name='add_buyer_post'),
    
    path('serviceproviders', ServiceProviderList.as_view(), name='serviceprovider_list'),
    path('serviceregistration', ServiceRegistrationList.as_view(), name='serviceregistration_list'),
    path('<int:pk>/view/', MapServiceDetailView.as_view(), name="map_service_detail"),  
    path('serviceproviderregistration', CreateServiceProviderProfile.as_view(), name='serviceprovider_registration'),
    path('create/service', CreateServiceView.as_view(), name='service_registration'),
    path('contactdetails', ContactDetailsList.as_view(), name='contactdetails_list'),
    path('logistics', LogiticsList.as_view(), name='logistics_list'),
    # path('storages', StorageList.as_view(), name='storage_list'),
    # path('packagings', PackagingList.as_view(), name='packaging_list'),
    # path('medicals', MedicalList.as_view(), name='medical_list'),
    path('soilsciences', SoilScienceList.as_view(), name='soilscience_list'),
    path('<int:pk>/approve/', approve_serviceprovider, name='aprrove'),    
    path('ajax/load-products/',load_products, name='ajax_load_products'),  # <-- this one here
    path('<int:pk>/edit/', UpdateServiceProviderProfile.as_view(), name="edit_service_provider_profile"),
    path('<int:pk>/viewprovider/', ServiceProviderProfileDetailView.as_view(), name="view_serviceprovider_profile"),
    path('<int:pk>/editservice/', EditServiceView.as_view(), name="edit_service_profile"),
    path('<int:pk>/viewservice/', ServiceDetailView.as_view(), name="view_service"),
    

    path('marketprice', MarketPriceList.as_view(), name='marketprice_list'),
   
]

urls.py
from django.urls import path
from apis.views import ( api_house_detail_view, api_house_detail_update)

app_name = 'landlord'

urlpatterns = [
    path('house/<int:id>/', api_house_detail_view, name="house-api"),
    path('house/update/<int:id>', api_house_detail_view, name="house-api")
    ,]

openmarket/models.py
from django.db import models
from django.contrib.auth.models import User
from common.models import(Region, District, County, SubCounty, Parish, Village, TimeStampedModel)
from common.choices import(GENDER_CHOICES,
                           MARITAL_STATUSES,REGISTER_STATUS,
                           STATUS,INVENTORY_STATUS, TYPE,
                           PAYMENT_MODE,
                           PAYMENT_OPTIONS,
                           YES_OR_NO,
                           EDUCATION_LEVEL,
                           SERVICE_CATEGORY)
from django.core.validators import RegexValidator
from farm.models import Enterprise
from phonenumber_field.modelfields import PhoneNumberField
from django.utils.translation import ugettext as _
from geopy.geocoders import Nominatim
from django.contrib.gis.db import models
from django.contrib.gis.db import models

from django.urls import reverse


class ProductCategory(models.Model):
    name = models.CharField(max_length=200,db_index=True, null=True)
    slug = models.SlugField(max_length=200,unique=True, null=True)

   
    class Meta:
        ordering = ('name',)
        verbose_name = 'productcategory'
        verbose_name_plural = 'productcategories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('unffeagents:view_market_detail_by_category',
                       args=[self.slug])

class Product(models.Model):
    category = models.ForeignKey(ProductCategory,related_name='products', null=True,on_delete=models.CASCADE)
    name = models.CharField(max_length=50, null=True)
    slug = models.SlugField(_('Local Name'), max_length=200, null=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d',blank=True)
    description = models.TextField(blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name



class Seller(models.Model):
    #personal information
    user = models.OneToOneField(User, on_delete=models.CASCADE, unique=True, related_name='seller',primary_key=True)
    seller_type = models.CharField(choices=TYPE,max_length=15, null=False)
    major_products = models.ManyToManyField(Product, blank=False)
    business_number = PhoneNumberField()   
    status = models.CharField(choices=REGISTER_STATUS, default='Pending', max_length=20,null=False)
    business_address = models.TextField(null=True, blank=True)
    gender = models.CharField(choices=GENDER_CHOICES, max_length=15, default=False)
    
      # handle approving of a seller
    approver = models.ForeignKey(User, on_delete=models.DO_NOTHING,related_name="seller_unffe_agent",null=True,blank=True)
    approved_date = models.DateTimeField(blank=True, null=True)


    class Meta:
        ordering = ('seller_type',)
        permissions = (
            ("can_approve_sellers", "Can approve Sellers"),
        )
    def __str__(self):
        return '{} {}'.format(self.user.first_name , self.user.last_name)



class SellerPost(models.Model):
    seller = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey('unffeagents.MarketPrice', on_delete=models.CASCADE)
    market = models.ForeignKey('unffeagents.Market', on_delete=models.CASCADE, null=True)
    quantity = models.FloatField(max_length=50, null=True)
    unit_of_measure = models.CharField(blank=False, max_length=100, null=True) # unit of measure like kilogram
    price_offer = models.DecimalField(max_digits=10, decimal_places=2)
    delivery_option = models.CharField(max_length=50)
    payment_options = models.CharField(choices=PAYMENT_OPTIONS, max_length=50, null=True)
    payment_mode = models.CharField(choices=PAYMENT_MODE, null=True, max_length=50)
    product_description = models.TextField(null=True, blank=True)
    product_image_1 = models.ImageField(null=True, blank=False)
    product_image_2 = models.ImageField(null=True, blank=True)

    class Meta:
        ordering = ('id',)

    def __str__(self):
        return self.product.product.name

    
    def get_absolute_url(self):
        return reverse('unffeagents:view_product_detail',
                       args=[self.id, self.product.product.slug])



class ProductOrdering(models.Model):
    product = models.ForeignKey(SellerPost, on_delete = models.CASCADE)
    buyer = models.CharField(max_length=25,null=True, blank=True)
    quantity = models.DecimalField(decimal_places=2, max_digits=20, blank=False)
    delivery_date = models.DateField(null=True, blank=True)
    delivery_address = models.TextField(blank=False, null=False)
    payment_mode = models.CharField(choices=PAYMENT_MODE, null=True, blank=True, max_length=25)
    payment_method = models.CharField(choices=PAYMENT_OPTIONS, max_length=25,null=True, blank=True)
    Additional_notes = models.TextField(blank=False, null=False)
    
    def __str__(self):
        return self.product

class BuyerPost(models.Model):
    name = models.CharField(max_length=50, null=True)
    current_location = models.CharField(max_length=50)
    product = models.CharField(max_length=50, null=True)
    quantity = models.FloatField(max_length=50, null=True)
    total_cost = models.DecimalField(max_digits=10, decimal_places=2)
    delivery_options = models.CharField(max_length=50, null=False)
    payment_options = models.CharField(choices=PAYMENT_OPTIONS, max_length=50, null=True)
    payment_mode = models.CharField(choices=PAYMENT_MODE, null=True, max_length=50)
    any_other_comment =models.TextField(null=True)

    class meta:
        ordering =("id",)



class Category(TimeStampedModel, models.Model):
    cat_name = models.CharField(max_length=255)
    
    def __str__(self):
        return self.cat_name


class ServiceProvider(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, unique=True, related_name='serviceprovider',primary_key=True)
    nin = models.CharField(_('National Identity Number (NIN)'),max_length=14, null=True, blank=False)
    service_provider_location = models.CharField(null=True, max_length=50)
    #business_number = PhoneNumberField(default=False)
    gender = models.CharField(choices=GENDER_CHOICES, max_length=15, default=False)
    #list_of_services_if_more_than_one = models.CharField(blank=True, max_length=50)
    is_the_service_available = models.BooleanField(choices=YES_OR_NO, null=True)
    #service_location = models.CharField(max_length=100, null=True)
    is_the_service_at_a_fee = models.BooleanField(choices=YES_OR_NO, null=True)
   # category = models.ManyToManyField(to='openmarket.Category', related_name='enterprise categories', choices=)
    category = models.ManyToManyField(Category, related_name='Categories')
    status = models.CharField(choices=STATUS, default='Pending', max_length=20,null=False)
    # handle approving of a farmer
    approver = models.ForeignKey(User, on_delete=models.DO_NOTHING,related_name="unffe_agent_service_provider",null=True,blank=True)
    approved_date = models.DateTimeField(blank=True, null=True)



    class meta:
        ordering =("nin")
        permissions = (
            ("can_approve_service_providers", "Can approve service providers"),
        )

class Service(models.Model):
    enterprise = models.CharField(max_length=50, null=True, blank=True)
    #This is a service provider

    service_provider = models.ForeignKey(ServiceProvider, on_delete=models.CASCADE, related_name='service',null=True)
    category = models.ForeignKey(Category, on_delete= models.CASCADE, null=True)
    service_name = models.CharField(max_length=200, null=True)
    #service_type = models.CharField(max_length=50, null=True)
    size =  models.FloatField(max_length=50, null=True,blank=True)
    terms_and_conditions = models.TextField(null=True, blank=True)
    availability_date = models.DateField(blank=True, null=True)
    availability_time = models.DateTimeField(auto_now_add=True, null=True)
    picture = models.ImageField(null=True, blank=True)
    description = models.TextField(blank=True)
    available_services = models.CharField(max_length=50, blank=True)
    rent = models.CharField(max_length=25, null=True, blank=True)
    name_of_storage_center = models.CharField(max_length=50, null=True,blank=True)
    location_of_storage_center = models.CharField(null=True, max_length=50, blank=True)
    certification_status = models.BooleanField(_('Is the Service Certified'),choices = YES_OR_NO, null=True, blank=True)
    vehicle_type = models.CharField(max_length=100, null = True, blank=True)
    vehicle_capacity = models.FloatField(max_length=50, null=True, help_text="capacity of your vehicle in tonnes", blank=True)
    location = models.PointField( srid=4326,null=True)
    others = models.CharField(_('Please state the category if its not among the above'), blank=True, null=True, max_length=100)
    driver_contact =  PhoneNumberField(null=True, blank=True)
    driver_name =  models.CharField(max_length = 100, null=True, blank = True)


    class meta:
        ordering =("service_type")
    
    @property
    def compute_location(self):
        geolocator = Nominatim(user_agent="ICT4Farmers", timeout=10)
        
       
        try:
            lat = str(self.location.y)
            lon = str(self.location.x)
            location = geolocator.reverse(lat + "," + lon)
            return '{}'.format(location.address)
        except:
            #location = str(self.location.y) + "," + str(self.location.x)
            return 'slow network, loading location ...'


class ContactDetails(models.Model):
    name = models.CharField(max_length=25, null=True)
    #phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number = PhoneNumberField() # validators should be a list


    class Meta:
        ordering =("name",)

class Logistics(models.Model):

openmarket/templates/create_seller_post.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
{% load crispy_forms_tags %}

            <!-- Container-fluid starts-->
            <div class="container-fluid">
                <div class="page-header">
                    <div class="row">
                        <div class="col">
                            <div class="page-header-left">
                                <h3>Post Product
                                   
                                </h3>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <ol class="breadcrumb float-right">
                                <li class="breadcrumb-item"><a href="{% url 'openmarket:sellerpost_list' %}"><i data-feather="home"></i></a></li>
                                <li class="breadcrumb-item">Products</li>
                                <li class="breadcrumb-item active">Post Product For Sale </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Container-fluid Ends-->

            <!-- Container-fluid starts-->
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="card tab2-card">
                            <div class="card-header">
                                <h5> Add Profile</h5>
                            </div>
                            <form id="form"  novalidate enctype="multipart/form-data" class="card-body" action="" method="post" data-products-url="{% url 'openmarket:ajax_load_products' %}">
                             {% csrf_token %}

                                <ul class="nav nav-tabs tab-coupon" id="myTab" role="tablist">
                                    <li class="nav-item"><a class="nav-link active show" id="productinfo-tab" data-toggle="tab" href="#productinfo" role="tab" aria-controls="productinfo" aria-selected="true" data-original-title="" title="">Product Information</a></li>
                                </ul>
                                <div class="tab-content" id="myTabContent">
                                    <div class="tab-pane fade active show" id="productinfo" role="tabpanel" aria-labelledby="productinfo-tab">
                                        <div class="row">
                                            <div class="col-xl-6 col-md-6">
                                                {{ form.market|as_crispy_field }}
                                            </div>
                                            <div class="col-xl-6 col-md-6">
                                                {{ form.product|as_crispy_field }}
                                            </div>
                                    
                                            <div class="col-xl-6 col-md-6">
                                                {{ form.quantity|as_crispy_field }}
                                            </div>
                                            
                                            <div class="col-xl-6 col-md-6">
                                                {{ form.price_offer|as_crispy_field }}
                                                <span class="error" id="error_2_id_price_offer"></span>
                                            </div>
                                            
                                            <div class="col-md-12">
                                                {{ form.delivery_option|as_crispy_field }}
                                            </div>
                                            <div class="col-md-6">
                                                {{ form.payment_options|as_crispy_field }}
                                            </div>
                                            <div class="col-md-6">
                                                {{ form.payment_mode|as_crispy_field }}
                                            </div>
                                            <div class="col-md-12">
                                                {{ form.product_description|as_crispy_field }}
                                            </div>
                                            <div class="col-md-6">
                                                {{ form.product_image_1|as_crispy_field }}
                                            </div>
                                            <div class="col-md-6">
                                                {{ form.product_image_2|as_crispy_field }}
                                            </div>
                                          
                                        </div>
                                    </div>
                                 </div>
                                                                    
                                <div style="overflow:auto;">
                                    <div style="float:right;">
                                        <input type='submit' class="btn btn-primary" value='save'/>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Container-fluid Ends-->
            {% endblock %}
            
{% block javascript %}
    <script type="text/javascript">
    {% for message in messages %}
    $(document).ready(function() {
        $.notify("{{message}}", "{{ message.tags }}", { position:"center" });
    });
    {% endfor %}

    var product = $('#id_product').find('option:selected').text();
    var val=product.split(' ');
    var range=val[1];
    var prices = range.split('-');
    var min_price = prices[0];
    var max_price = prices[1];
   
    
    $('#id_price_offer').on('mouseout', function (e) {
        $('#error_2_id_price_offer').val("Enter an amount with in the price range of the product");
        if(parseInt($('#id_price_offer').val()) < parseInt(min_price)){
            $('#error_2_id_price_offer').text("Enter an amount with in the price range of the product");
            
        }
        else if(parseInt($('#id_price_offer').val()) > parseInt(max_price)){
            $('#error_2_id_price_offer').text("Enter an amount with in the price range of the product");
        }
        else{
            $('#error_2_id_price_offer').text('');
        }
       
     });
       //load districts
    $("#id_market").change(function () {
      var url = $("#form").attr("data-products-url");  // get the url of the `load_cities` view
      var marketId = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'market': marketId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_product").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });
    </script>
{% endblock %}

openmarket/templates/packaging_list.html
<html><body>
    <h1>Packaging</h1>
    <ul>
        {% for packaging in packaging %}
        <li>{{ packaging.name }}</li>
        {% endfor %}
    </ul>
    </body></html>

openmarket/templates/product_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<!-- Container-fluid starts-->
<div class="container-fluid">
  <div class="page-header">
    <div class="row">
      <div class="col-lg-6">
        <div class="page-header-left">
          <h3>Products List
            {% if perms.openmarket.add_product %}
            <small><a class="add-new" href="{% url 'openmarket:create_product' %}">

                Add new
              </a></small>
           {% endif %}
          </h3>
        </div>
      </div>
      <div class="col-lg-6">
        <ol class="breadcrumb float-right">
          <li class="breadcrumb-item"><a href="{% url 'common:home' %}"><i data-feather="home"></i></a></li>
          <li class="breadcrumb-item">Product profile</li>
          <li class="breadcrumb-item active">Product profile List</li>
        </ol>
      </div>
    </div>
  </div>
</div>

<!-- Container-fluid Ends-->



<!-- bootstrap table begin here -->
<div id="toolbar">
  {% if request.user.is_superuser or perms.openmarket.delete_product %}
  <button id="remove" class="btn btn-danger" title="Delete" disabled>
    <i class="fa fa-trash"></i>
  </button>

  {% endif %}

</div>
<table id="table" data-toggle="table" data-show-toggle="true" data-search="true" data-show-refresh="true"
  data-show-fullscreen="true" data-show-columns="true" data-show-columns-toggle-all="true" data-show-export="true"
  data-click-to-select="true" data-minimum-count-columns="2" data-show-pagination-switch="true" data-pagination="true"
  data-id-field="id" data-toolbar="#toolbar" data-export-types="[‘png’, ‘csv’,‘doc’, ‘excel’, ‘xlsx’, ‘pdf’]"
  data-page-list="[10, 25, 50, 100, all]" data-url="/openmarket/api/products/" data-response-handler="responseHandler">
  <thead>
    <tr>
      <th data-field="state" data-checkbox="true"></th>
      <th data-field="name" data-sortable="true">Name</th>
      <th data-field="slug" data-sortable="true">Local Name</th>
      <th data-field="image" data-visible="true" data-formatter="imageFormatter" data-sortable="true">Image</th>
      <th data-field="description" data-sortable="true">Description</th>
    
      <th data-field="date_created" data-sortable="true">Date Created</th>
      
      <th data-formatter="operateFormatter" class="text-center">Action</th>
    </tr>
  </thead>
</table>
<!--bootstrap table ends here-->

{% endblock %}

<!-- latest jquery-->
{% block javascript %}
<script>
  var $table = $('#table')
  var $remove = $('#remove')
  var $approve = $('#approve')
  var $decline = $('#decline')
  var selections = []

  function getIdSelections() {
    return $.map($table.bootstrapTable('getSelections'), function (row) {
      return row.id
    })
  }

  function responseHandler(res) {
    $.each(res.rows, function (i, row) {
      row.state = $.inArray(row.id, selections) !== -1
    })
    return res
  }



  function operateFormatter(value, row, index) {
    var url = "/openmarket/" + row.id + "/edit/product/"
    
    return [
      {% if request.user.is_superuser or perms.openmarket.change_product %}
  '<a class="Edit " href="' + url + '" title="Update">',
    '<i class="fa fa-edit"></i>',
    '</a>  ',
    {% endif %}

    ].join('')
  }
  function imageFormatter(value, row) {
    var url = row.image;
    return '<img class="img-thumbnail" style="height:80px; width:80px;" src="' + url + '">'
  }



  ///used cookies to get crsf token
  function getCookie(c_name) {
    if (document.cookie.length > 0) {
      c_start = document.cookie.indexOf(c_name + "=");
      if (c_start != -1) {
        c_start = c_start + c_name.length + 1;
        c_end = document.cookie.indexOf(";", c_start);
        if (c_end == -1) c_end = document.cookie.length;
        return unescape(document.cookie.substring(c_start, c_end));
      }
    }
    return "";
  }

  function initTable() {

    $table.on('check.bs.table uncheck.bs.table ' +
      'check-all.bs.table uncheck-all.bs.table',
      function () {
        $remove.prop('disabled', !$table.bootstrapTable('getSelections').length)
        $approve.prop('disabled', !$table.bootstrapTable('getSelections').length)
        $decline.prop('disabled', !$table.bootstrapTable('getSelections').length)

        // save your data, here just save the current page
        selections = getIdSelections()
        // push or splice the selections if you want to save all data selections
      })
    $table.on('all.bs.table', function (e, name, args) {
      console.log(name, args)
    })
    ///multiple delete
    $remove.click(function () {
      var ids = getIdSelections()
      $remove.prop('disabled', true)

      swal({
        title: "Are you sure?",
        text: "Once deleted, you will not be able to recover these records!",
        icon: "warning",
        buttons: true,
        dangerMode: true,
      })
        .then((willDelete) => {
          if (willDelete) {
            for (id = 0; id < ids.length; id++) {
              console.log(ids[id]);

              $.ajax({
                url: "/openmarket/api/products/" + ids[id],
                data: {},
                headers: { "X-CSRFToken": getCookie("csrftoken") },
                type: 'DELETE',
                contentType: 'application/json',
                success: function (result) {
                  console.log('deleted successfule');
                },
              });
              swal("Your record/s have been deleted successfully!", {
                icon: "success",
              }).then(() => {
                window.location.reload()
              });
              ;
            }
          } else {
            swal("You have cancelled the deletion of records!");
          }
        });

    })



  }

  $(function () {
    initTable()

    $('#locale').change(initTable)
  })


</script>
{% endblock %}

openmarket/templates/products_dropdown_list_options.html
<option value="">--please select--</option>
{% for product in products %}
<option value="{{ product.pk }}">{{ product.get_product }}</option>
{% endfor %}

openmarket/templates/service_provider_reg_email.html
{% extends 'root_email.html' %}
{% block heading %}
Dear {{ user.first_name }} {{user.last_name}},
{% endblock heading %}
{% block content_body %}
Your account as a service provider has been created successfully
<br>

If you think, it's not you, then just ignore this email.
<br>
Kind Regards,<br>
ICT4Farmers Team
{% endblock content_body %}

openmarket/templates/storage_list.html
<html><body>
    <h1>Storage</h1>
    <ul>
        {% for storage in storages %}
        <li>{{ storage.name }}</li>
        {% endfor %}
    </ul>
    </body></html>