common/urls.py
from django.contrib.auth import views as auth_views
from common.views import (
    HomePage, account_activation_sent, activate, SignUpView, ProfileView,
    ForgotPasswordView, load_districts, load_counties,load_sub_counties,
    load_parishes,load_villages, activate,ChangePasswordView,account_activated,
    OpenMarketHomePage
)

from django.urls import path,include
from rest_framework import routers
from . import views



router = routers.DefaultRouter()

router.register(r'register', views.UserViewSet,'users')
router.register(r'groups', views.GroupViewSet,'groups')
router.register(r'counties',views.CountyViewSet,'counties')
router.register(r'sub_counties',views.SubCountyViewSet,'sub_counties')
router.register(r'districts', views.DistrictViewSet,'districts')
router.register(r'parishes',views.ParishViewSet,'parishes')
router.register(r'villages',views.VillageViewSet, 'villages')
router.register(r'post_users', views.PostUserDataViewSet, 'post_users')
router.register(r'profiles', views.PostProfileViewSet, 'profiles')
router.register(r'regions',views.RegionViewSet, 'regions')


app_name ='common'

urlpatterns = [
    path('api/', include(router.urls)),
    path('',OpenMarketHomePage.as_view(), name='open_market'),
    path('home', HomePage.as_view(), name='home'),
    path('account/change_password', ChangePasswordView.as_view(), name='change_password'),
    path('account_activation_sent/', account_activation_sent, name='account_activation_sent'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('activate/<uidb64>/<token>/', activate, name='activate'),
    path('account/activated', account_activated, name='activated'),
    path('forgot-password/', ForgotPasswordView.as_view(), name='forgot_password'),
    path('<int:pk>/view/profile', ProfileView.as_view(), name="view_profile"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # load districts url
    path('ajax/load-districts/', load_districts, name='ajax_load_districts'),
    path('ajax/load-counties/', load_counties, name='ajax_load_counties'),
    path('ajax/load-sub_counties/', load_sub_counties, name='ajax_load_sub_counties'),
    path('ajax/load-parishes/', load_parishes, name='ajax_load_parishes'),
    path('ajax/load-villages/', load_villages, name='ajax_load_villages'),

   
] 

ict4farmers/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from common .views import LoginView, LogoutView
from django.conf.urls.static import static
from django.conf import settings
from common.views import obtain_auth_token 
from rest_framework_swagger.views import get_swagger_view
schema_view = get_swagger_view(title="ICT4Farmers API Docs")

urlpatterns = [
    path('admin/', admin.site.urls),
    # api documentation
    path('api/docs', schema_view),
    # authentication urls
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # api authentication urls
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),

    # common urls
    path('', include('common.urls', namespace="common")),

    # open market urls
    path('openmarket/', include('openmarket.urls', namespace="openmarket")),

    # farm urls
  
    path('farm/', include('farm.urls', namespace="farm")),

    # farmer urls
   
    path('farmer/', include('farmer.urls', namespace="farmer")),

    # unffeagents urls
    path('unffeagents/', include('unffeagents.urls', namespace="unffeagents")),

    # open weather urls
   
    path('weather/', include('weather.urls', namespace="weather")),

    # resorce sharing urls
    path('resourcesharing/', include('resourcesharing.urls', namespace="resourcesharing")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

unffeagents/urls.py
from django.urls import include, path
from rest_framework import routers
from . import views
from .views import (AgentProfileList,ProductOrderingView,ProductOrderingList,ProductDetailView, MarketList, MarketPriceList, CreateMarketPrice,EditMarketPriceView,
NoticeList,CreateAgentProfile, CreateNoticeView,EditNoticeView, EditAgentProfileView,
CallList,EquiryList,CreateEquiryView,EditEquiryView,UsersList,CreateMarket,MarketDetailView,
EditMarketView, CreateMarketPrice, EditMarketPriceView)


router = routers.DefaultRouter()
router.register(r'productordering', views.ProductOrderingViewSet)
router.register(r'agentprofile', views.AgentProfileViewSet, basename='agents')
router.register(r'market', views.MarketViewSet, basename='markets_api')
router.register(r'marketprice', views.MarketPriceViewSet)
router.register(r'notice', views.NoticeViewSet)
router.register(r'call', views.CallerViewSet)
router.register(r'response', views.ResponseViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.

app_name = 'unffeagents'

urlpatterns = [
    path('api/', include(router.urls)),
    path('agentprofile', AgentProfileList.as_view(), name='agentprofile_list'),
    path('create/agentprofile', CreateAgentProfile.as_view(), name="create_agentprofile"),
    path('create/enquiry/<slug:session_id>', CreateEquiryView.as_view(), name="create_enquiry"),
    path('<int:pk>/edit/agentprofile', EditAgentProfileView.as_view(), name="edit_agent_profile"),
    path('<int:pk>/edit/enquiry', EditEquiryView.as_view(), name="edit_equiry"),
    path('market', MarketList.as_view(), name='market_list'),
    path('create/market', CreateMarket.as_view(), name='add_market'),
    path('<int:pk>/edit/market/',EditMarketView.as_view(), name='edit_market'),
    path('marketprice', MarketPriceList.as_view(), name='marketprice_list'),
    path('create/market/price', CreateMarketPrice.as_view(), name='add_market_price'),
    path('<int:pk>/edit/market/price',EditMarketPriceView.as_view(), name='edit_market_price'),

    path('<int:pk>/view/market', MarketDetailView.as_view(), name="view_market_detail"),
    path('<slug:category_slug>/', MarketDetailView.as_view(), name='view_market_detail_by_category'),
    path('<int:pk>/<slug:slug>/', ProductDetailView.as_view(), name="view_product_detail"),


    path('ordering/<int:product_pk>', ProductOrderingView.as_view(), name="productordering"), 
    path('productordering', ProductOrderingList.as_view(), name='productordering_list'), 

    path('alert&notification', NoticeList.as_view(), name='notice_list'),
    path('calls',CallList.as_view(), name='calls'),
    path('enquiries',EquiryList.as_view(), name='enquiries'),
    path('create/alert&notification', CreateNoticeView.as_view(), name='add_notice'),
    path('<int:pk>/edit/alert&notification', EditNoticeView.as_view(), name="edit_notice"),
    path('users', UsersList.as_view(), name="users_list"),

]

urls.py
from django.urls import path
from apis.views import ( api_house_detail_view, api_house_detail_update)

app_name = 'landlord'

urlpatterns = [
    path('house/<int:id>/', api_house_detail_view, name="house-api"),
    path('house/update/<int:id>', api_house_detail_view, name="house-api")
    ,]

common/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _
import phonenumbers
from phonenumber_field.modelfields import PhoneNumberField
from common.choices import(GENDER_CHOICES)
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.conf import settings
# Create your models here.

class TimeStampedModel(models.Model):
    """
    Abstract model class that includes timestamp fields
    """
    created = models.DateTimeField(
        verbose_name=_('Created'),
        auto_now=True)
    modified = models.DateTimeField(
        verbose_name=_('Modified'),
        auto_now=True)

    # pylint: disable=too-few-public-methods
    class Meta:
        """
        Meta options for TimeStampedModel
        """
        abstract = True


class Region(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)

    def __str__(self):
        return self.name


class District(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)
    region = models.ForeignKey(Region, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class County(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)
    district = models.ForeignKey(District, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class SubCounty(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)
    county = models.ForeignKey(County, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Parish(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)
    sub_county = models.ForeignKey(SubCounty, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Village(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)
    parish = models.ForeignKey(Parish, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

#Extending the auth_user table
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    phone_number = PhoneNumberField(blank=False, null=False)
    phone_2 = PhoneNumberField(_('Phone number 2'), blank=True, null=True)
    home_address = models.TextField(max_length=100, blank=True)
    gender = models.CharField(choices=GENDER_CHOICES, max_length=15)
    profile_pic = models.ImageField(null=True, blank=True)
     # moved users location to profile to avoid redundancy
    region = models.ForeignKey(Region, on_delete=models.CASCADE, null=True, blank=False)
    district = models.ForeignKey(District, on_delete=models.CASCADE, null=True, blank=False)
    county = models.ForeignKey(County, on_delete=models.CASCADE, null=True, blank=False)
    sub_county = models.ForeignKey(SubCounty, on_delete=models.CASCADE, null=True, blank=False)
    parish = models.ForeignKey(Parish, on_delete=models.CASCADE, null=True, blank=True)
    village = models.ForeignKey(Village, on_delete=models.CASCADE, null=True, blank=True)


    def __str__(self):
        return '{} {}'.format(self.user.first_name, self.user.last_name)

    def get_full_name(self):
        return '{} {}'.format(self.user.first_name, self.user.last_name)

unffeagents/models.py
from django.db import models
from django.contrib.auth.models import User, Group
from openmarket.models import Product
from phonenumber_field.modelfields import PhoneNumberField
from django.utils.translation import ugettext as _
from common .models import (District,County,Region,SubCounty, Parish,Village)
from common .models import TimeStampedModel
from farm .models import Sector
from django.contrib.gis.db import models
from geopy.geocoders import Nominatim


# Create your models here.
class AgentProfile(models.Model):
    SPECIFIC_ROLE = (
        (None, "--please select--"),
        ('account manager', 'Account Manager'),
        ('market manager', 'Market Manager'),
        ('call centre agent', 'Call Centre Agent'),
        ('notifications and alerts', 'Notifications and Alerts'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='agent')
    contact = PhoneNumberField(blank=False)
    # agent address
    region = models.ForeignKey(Region, on_delete=models.CASCADE)
    district = models.ForeignKey(District, on_delete=models.CASCADE)
    specific_role = models.CharField(max_length = 50, choices=SPECIFIC_ROLE)

    def __str__(self):
        return self.specific_role




class Market(models.Model):
    market_name = models.CharField(max_length=100, blank = False)
    market_description = models.TextField(max_length=600, blank=False)
    location = models.PointField( srid=4326,null=True)
   

    @property
    def compute_location(self):
        geolocator = Nominatim(user_agent="ICT4Farmers", timeout=10)
        lat = str(self.location.y)
        lon = str(self.location.x)
       
        try:

            location = geolocator.reverse(lat + "," + lon)
            return '{}'.format(location.address)
        except:
            location = str(self.location.y) + "," + str(self.location.x)
            return 'slow network, loading location ...'

    def __str__(self):
        return self.market_name


class MarketPrice(TimeStampedModel, models.Model):
    market = models.ForeignKey(Market, blank = False, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='unffeagent')
    product = models.ForeignKey(Product, blank=False, on_delete=models.CASCADE) # let it be product per price
    unit_of_measure = models.CharField(blank=False, max_length=100) # unit of measure like kilogram
    max_price = models.DecimalField(decimal_places=2, max_digits=20, blank=False)
    min_price = models.DecimalField(decimal_places=2, max_digits=20, blank=False)
    

    def __str__(self):
        return '{} {}-{}'.format(self.product.name, self.min_price, self.max_price)

    @property
    def get_product(self):
        return '{} {}-{}'.format(self.product.name, self.min_price, self.max_price)
        



class Notice(TimeStampedModel, models.Model):
    # sector
    sector = models.ManyToManyField(Sector, related_name='notice_sectors', blank=True)
        # location
    region = models.ManyToManyField(Region, related_name='target_regions')
    district = models.ManyToManyField(District, related_name='notice_districts', blank=True)
    county = models.ManyToManyField(County, related_name='notice_counties', blank=True)
    sub_county = models.ManyToManyField(SubCounty, related_name='notice_sub_counties', blank=True)
    parish = models.ManyToManyField(Parish, related_name='notice_parishes', blank=True)
    village = models.ManyToManyField(Village, related_name='notice_villages', blank=True)
     
    # notice details
    notice_title = models.CharField(max_length=200, blank = False, null=False)
    display_up_to = models.DateTimeField(blank = False)
    posted_by = models.ForeignKey(User, on_delete=models.CASCADE)
    target_audience = models.ManyToManyField(Group, related_name='target_groups')
    description = models.TextField(max_length=300, blank=False)
  

    def __str__(self):
        return self.notice_title

# adding models for call response

class Call(TimeStampedModel, models.Model):
    session_id = models.CharField(primary_key=True,unique=True, max_length=200, null=False, blank=False)
    phone = PhoneNumberField(blank=False, null=True)
    call_date = models.DateTimeField(null=True, blank=True)
    call_type = models.CharField(max_length=200, null=True, blank=True)
    active = models.IntegerField(null=True)
    recording_url = models.URLField(null=True, blank=True)
    agent_phone = models.CharField(max_length=12, null=True, blank=True)
    call_duration = models.DurationField(null=True, blank=True)

    def __str__(self):
        return str(self.session_id)

# converstion record
class CallRsponse(TimeStampedModel, models.Model):
    QUESTION_TYPE=(
        (None, '--please select--'),
        ('enterprise','Enterprise Selection'),
        ('farmer','Farmer Information'),
        ('farm','Farm Information'),
        ('service providers','Service Providers'),
        ('services','Services'),
        ('open market','Open Market'),
        ('seller','Seller Information'),
        ('product','Products'),
        ('resource sharing','Resource Sharing'),
        ('alerts','Alerts and Opportunities'),
        ('weather','Micro Weather Services'),
        ('agents','UNFFE Agents')
    )
    call = models.OneToOneField(Call, on_delete=models.CASCADE, related_name='responses', null=True)
    agent = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    caller_name = models.CharField(_('Caller\'s Name'),max_length=200, null=True,blank=False)
    caller = PhoneNumberField(_('Phone Number'),blank=False, null=True)
    type_of_question =  models.CharField(max_length=50, null=True, blank=False, choices=QUESTION_TYPE)
    question = models.TextField(null=True)
    solution = models.TextField(null=True)
    called_from = models.ForeignKey(District, null=True, blank=False, on_delete=models.DO_NOTHING)

    def __str__(self):
        return str(self.type_of_question)

unffeagents/templates/agentprofile_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
   <!-- Container-fluid starts-->
   <div class="container-fluid">
    <div class="page-header">
        <div class="row">
            <div class="col-lg-6">
                <div class="page-header-left">
                    <h3>Agents List
                      {% if request.user.is_superuser or perms.unffeagents.add_agentprofile %}
                        <small><a class="add-new" href="{% url 'unffeagents:create_agentprofile' %}">Add new</a></small>
                        {% endif %}
                    </h3>
                </div>
            </div>
            <div class="col-lg-6">
                <ol class="breadcrumb float-right">
                    <li class="breadcrumb-item"><a href="{% url 'common:home' %}"><i data-feather="home"></i></a></li>
                    <li class="breadcrumb-item">UNFFE</li>
                    <li class="breadcrumb-item active">Agents List</li>
                </ol>
            </div>
        </div>
    </div>
</div>




<!-- bootstrap table begin here -->
<div id="toolbar">
  {% if request.user.is_superuser or perms.unffeagents.delete_agentprofile %}
  <button id="remove" class="btn btn-danger" disabled>
    <i class="fa fa-trash"></i> Delete
  </button>
  {% endif %}
</div>
<table
   id="table"
   data-toggle="table"
  data-show-toggle="true"
  data-search="true"
  data-show-search-button="true"
  data-show-refresh="true"
  data-show-fullscreen="true"
  data-show-columns="true"
  data-show-columns-toggle-all="true"
  data-show-export="true"
  data-click-to-select="true"
  data-minimum-count-columns="2"
  data-show-pagination-switch="true"
  data-pagination="true"
  data-id-field="id"
  data-total-field="count"
  data-data-field="results"
  data-toolbar="#toolbar"
  data-side-pagination="server"
  data-server-sort="false"
  data-page-list="[10, 25, 50, 100, all]"
  data-export-types="[‘png’, ‘csv’,‘doc’, ‘excel’, ‘xlsx’, ‘pdf’,'json']"
  data-url="/unffeagents/api/agentprofile/"
  data-response-handler="responseHandler">
  <thead>
    <tr>
      {% if request.user.is_superuser or perms.unffeagents.delete_agentprofile %}
      <th data-field="state" data-checkbox="true"></th>
      {% endif %}
      <th data-field="user_names" data-sortable="true"> Names</th>
      <th data-field="contact" data-sortable="true"> Contact</th>
      <th data-field="region" data-sortable="true">Region</th>
      <th data-field="district" data-sortable="true">District</th>
      <th data-field="region" data-sortable="true">Region</th>
      <th data-field="specific_role" data-sortable="true">Role</th>
      <th data-formatter="operateFormatter"  class="text-center">Action</th>
                
    </tr>
  </thead>
</table>
 <!--bootstrap table ends here-->
 {% endblock %}
 {% block javascript %}
<script>
  var $table = $('#table');
  var $remove = $('#remove')
  var selections = []

  function getIdSelections() {
    return $.map($table.bootstrapTable('getSelections'), function (row) {
      return row.id
    })
  }
  function responseHandler(res) {
    $.each(res.rows, function (i, row) {
      row.state = $.inArray(row.id, selections) !== -1
    })
    return res
  }
  //displays an image
    function imageFormatter(value, row) {
      var url =row.image;
    return '<img class="img-thumbnail" src="'+url+'">'
  }
  function operateFormatter(value, row, index) {
    console.log(row.id);
    var url ="/unffeagents/"+row.id+"/edit/agentprofile";

    return [
    {% if request.user.is_superuser or perms.unffeagents.change_agentprofile %}
      '<a class="Edit " href="'+url+'" title="Edit">',
      '<i class="fas fa-edit"></i>',
      '</a>  ',
        {% endif %}
       
    ].join('')
  }

  ///used cookies to get crsf token
  function getCookie(c_name)
    {
      if (document.cookie.length > 0)
        {
          c_start = document.cookie.indexOf(c_name + "=");
            if (c_start != -1)
         {
            c_start = c_start + c_name.length + 1;
            c_end = document.cookie.indexOf(";", c_start);
            if (c_end == -1) c_end = document.cookie.length;
            return unescape(document.cookie.substring(c_start,c_end));
         }
     }
      return "";
   }
   function initTable() {

$table.on('check.bs.table uncheck.bs.table ' +
  'check-all.bs.table uncheck-all.bs.table',
function () {
  $remove.prop('disabled', !$table.bootstrapTable('getSelections').length)


  // save your data, here just save the current page
  selections = getIdSelections()
  // push or splice the selections if you want to save all data selections
})
$table.on('all.bs.table', function (e, name, args) {
  console.log(name, args)
})
///multiple delete
$remove.click(function () {
  var ids = getIdSelections()
  $remove.prop('disabled', true)

  swal({
title: "Are you sure?",
text: "Once deleted, you will not be able to recover these records!",
icon: "warning",
buttons: true,
dangerMode: true,
})
.then((willDelete) => {
if (willDelete) {
for(id=0; id<ids.length; id++){
    console.log(ids[id]);

$.ajax({
    url: "/unffeagents/api/agentprofile/"+ids[id],
    data: {},
    headers:{"X-CSRFToken": getCookie("csrftoken")},
    type: 'DELETE',
    contentType: 'application/json',
    success: function(result) {
      console.log('deleted successfule');
    },
   });
swal("Your record/s have been deleted successfully!", {
  icon: "success",
}).then(() =>{
        window.location.reload()});
;}
} else {
swal("You have cancelled the deletion of records!");
}
});

})






}

$(function() {
initTable()

$('#locale').change(initTable)
})




</script>
 

 {% endblock %}

unffeagents/templates/create_enquiry.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
{% load crispy_forms_tags %}


            <!-- Container-fluid starts-->
            <div class="container-fluid">
                <div class="page-header">
                    <div class="row">
                        <div class="col">
                            <div class="page-header-left">
                                <h3>Add Enquiry
                                </h3>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <ol class="breadcrumb float-right">
                                <li class="breadcrumb-item"><a href="{% url 'unffeagents:enquiries' %}"><i data-feather="home"></i></a></li>
                                <li class="breadcrumb-item add-new">Call Center</li>
                                <li class="breadcrumb-item active">Add Enquiries </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Container-fluid Ends-->

            <!-- Container-fluid starts-->
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="card tab2-card">
                            <div class="card-header">
                                <h5> Add Enquiry</h5>
                         
                            </div>
                            <form method="POST" id="form"  novalidate enctype="multipart/form-data" class="card-body">
                                {% csrf_token %}
                                <div class="row">
                                    
                                    <div class=" col-md-12">
                                        {{ form.caller_name|as_crispy_field }}
                                    </div>
                               
                                
                                    
                                    <div class="col-md-6">
                                        {{ form.called_from|as_crispy_field }}
                                    </div>
                                    <div class="col-md-6">
                                        {{ form.type_of_question|as_crispy_field }}
                                    </div>
                                    <div class="col-xl-12 col-md-12">
                                        {{ form.question|as_crispy_field }}
                                    </div>
                                    
                             
                                    <div class="col-xl-12 col-md-12">
                                        {{ form.solution|as_crispy_field }}
                                    </div>
                                    
                                  
                                </div>
                              
                                <div class="float-right">
                                    <input type="submit" value="Submit" class="btn btn-primary">


                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                </div>
            
            <!-- Container-fluid Ends-->
            {% endblock %}
           

<!--select 2-->
<!-- latest jquery-->
{% block javascript %}
<!--select 2-->
<script type="text/javascript">

    $(document).ready(function () {
        $('#id_district').select2();
        $('#id_county').select2();
        $('#id_sub_county').select2();
        $('#id_parish').select2();
        $('#id_village').select2();
        $('#id_target_audience').select2();

    });
  
  
  </script>
{% endblock %}

unffeagents/templates/create_notification.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
{% load crispy_forms_tags %}


            <!-- Container-fluid starts-->
            <div class="container-fluid">
                <div class="page-header">
                    <div class="row">
                        <div class="col">
                            <div class="page-header-left">
                                <h3>Create Notification
                                </h3>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <ol class="breadcrumb float-right">
                                <li class="breadcrumb-item"><a href="{% url 'unffeagents:notice_list' %}"><i data-feather="home"></i></a></li>
                                <li class="breadcrumb-item add-new">Notifications</li>
                                <li class="breadcrumb-item active">Add Notification </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Container-fluid Ends-->

            <!-- Container-fluid starts-->
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="card tab2-card">
                            <div class="card-header">
                                <h5> Add Notification</h5>
                         
                            </div>
                            <form method="POST" id="form"  novalidate enctype="multipart/form-data" class="card-body">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-xl-12 col-md-12">
                                        {{ form.region|as_crispy_field }}
                                    </div>
                                    <div class="col-xl-12 col-md-12">
                                        {{ form.sector|as_crispy_field }}
                                    </div> 
                                  
                                    <div class="col-xl-6 col-md-6">
                                        {{ form.district|as_crispy_field }}
                                    </div>
                                   
                                   
                                    <div class="col-md-6">
                                        {{ form.county|as_crispy_field }}
                                    </div>
                                     
                                    <div class="col-xl-6 col-md-6">
                                        {{ form.sub_county|as_crispy_field }}
                                    </div>
                                    
                                    <div class="col-xl-6 col-md-6">
                                        {{ form.parish|as_crispy_field }}
                                    </div>
                                    <div class="col-xl-12 col-md-12">
                                        {{ form.village|as_crispy_field }}
                                    </div>
                               
                                    <div class="col-xl-6 col-md-6">
                                        {{ form.target_audience|as_crispy_field }}
                                    </div>
                                    <div class="col-xl-6 col-md-6">
                                        {{ form.display_up_to|as_crispy_field }}
                                    </div>
                                    <div class="col-xl-12 col-md-12">
                                        {{ form.notice_title|as_crispy_field }}
                                    </div>
                                    
                             
                                    <div class="col-xl-12 col-md-12">
                                        {{ form.description|as_crispy_field }}
                                    </div>
                                    
                                  
                                </div>
                              
                                <div class="float-right">
                                    <input type="submit" value="Send" class="btn btn-primary">


                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                </div>
            
            <!-- Container-fluid Ends-->
            {% endblock %}
           

<!--select 2-->
<!-- latest jquery-->
{% block javascript %}
<!--select 2-->
<script type="text/javascript">

    $(document).ready(function () {
        $('#id_district').select2();
        $('#id_county').select2();
        $('#id_sub_county').select2();
        $('#id_parish').select2();
        $('#id_village').select2();
        $('#id_target_audience').select2();

    });
  
  
  </script>
{% endblock %}

unffeagents/templates/notice_email.html
{% extends 'root_email.html' %}
{% block heading %}
Dear {{ user.first_name }} {{user.last_name}},
{% endblock heading %}
{% block content_body %}

{{message}}
<br>

If you think, it's not you, then just ignore this email.
<br>
Kind Regards,<br>
ICT4Farmers Team
{% endblock content_body %}